GET localhost:8080

###

GET localhost:8080/index.html

###

GET localhost:8080/user/create?userId=javajigi&password=password&name=JaeSung&email=javajigi%40slipp.net

###

POST localhost:8080/user/create
Content-Type: application/x-www-form-urlencoded

#userId=javajigi&password=password&name=JaeSung&email=javajigi%40slipp.net
userId=admin&password=admin&name=Admin&email=admin%40google.com


###

POST localhost:8080/user/login
Content-Type: application/x-www-form-urlencoded

userId=javajigi&password=password

###

